apiVersion: v2
name: minecraft-exporter
icon: https://dirien.github.io/minecraft-prometheus-exporter/img/chart-logo.png
description: A Helm chart for prometheus minecraft exporter
keywords:
  - minecraft
  - prometheus
  - exporter
type: application
version: 0.11.1
appVersion: 0.20.0
home: https://github.com/dirien/minecraft-prometheus-exporter/
sources:
  - https://github.com/dirien/minecraft-prometheus-exporter/
maintainers:
  - email: engin.diri@ediri.de
    name: dirien

annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - update exporter to 0.20.0
  artifacthub.io/images: |
    - name: minecraft-exporter
      image: ghcr.io/dirien/minecraft-exporter:0.20.0
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: dirien
      email: engin.diri@ediri.de
